### ISSUE TITLE
poloqweqwe

### ISSUE THREAD

**Issue by rjdelrio** [rjdelrio/polo877#25]
te poajjdahfj
kfasbfsafdjjasfkjdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd

exeption chatError men

**Comment by rjdelrio** [comment]
polopolo asw 23 aqui estaria en link brigido

**Comment by rjdelrio** [comment]
https://stackoverflow.com/questions/36925607/java-voice-chat-error

**Comment by rjdelrio** [comment]
oooo esto podria no estar bn

**Comment by Tomizaky** [comment]
dale

**Comment by npinochet** [comment]
STAR TREK BABY
